### ISSUE TITLE
ERROR: Failed to resolve: com.github.smhdk:KM-Recyclerview-Sticky-Header:v1.0.0

### ISSUE THREAD

**Issue by Eldhopj** [smhdk/KM-Recyclerview-Sticky-Header#3]
Cannot able to add this library 
Android studio ver : 3.3.2
Grade : 4.10.1
![screen shot 2019-03-06 at 3 12 59 pm](https://user-images.githubusercontent.com/21988910/53871542-748d6500-4022-11e9-813f-1fe25971b9ad.png)

**Comment by smhdk** [comment]
> Cannot able to add this library
> Android studio ver : 3.3.2
> Grade : 4.10.1
> ![screen shot 2019-03-06 at 3 12 59 pm](https://user-images.githubusercontent.com/21988910/53871542-748d6500-4022-11e9-813f-1fe25971b9ad.png)

Hi @Eldhopj 

Add this **maven { url 'https://jitpack.io' }** in your root build.gradle at the end of repositories as follows

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
